{{- if and .Values.rbac.create (not .Values.rbac.namespaced) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "agentops-console.fullname" . }}
  labels:
    {{- include "agentops-console.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "agentops-console.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "agentops-console.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
