{{- if and .Values.rbac.create .Values.rbac.namespaced -}}
{{- $fullName := include "agentops-console.fullname" . -}}
{{- $labels := include "agentops-console.labels" . -}}
{{- range .Values.rbac.watchNamespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $fullName }}
  namespace: {{ . }}
  labels:
    {{- $labels | nindent 4 }}
rules:
  {{- include "agentops-console.rbacRules" $ | nindent 2 }}
{{- end }}
{{- end }}
